config/routes.rb
Rails.application.routes.draw do
	get 'new/todos/modal', to: 'todos#new_modal', :as => :new_modal
	resources :todos
	root 'static_pages#home'
	get  '/about',   to: 'static_pages#about'
	get '/todos', 	  to: 'todos#index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about 
  end 
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index 
		@todos = Todo.all
	end

	def show
	end 

	def new 
		@todo = Todo.new
	end 

	def create 
		@todo = Todo.create(todo_params)
		redirect_to todos_path
	end

	def edit
		@todo = Todo.find(params[:id])
		respond_to do |format|
	    	format.html
	    	format.js
	  	end
	end

	def update 
		@todo = Todo.find(params[:id])
		@todo.update(todo_params)
		redirect_to todos_path
	end

	def destroy
  		@todo = Todo.find(params[:id])
  		@todo.destroy
  		redirect_to todos_path
	end

	def new_modal 
		@todo = Todo.new
		respond_to do |format|
	    	format.html
	    	format.js
	  	end
	end

	private 

	def todo_params
		params.require(:todo).permit(:item)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_edit.html.erb
<%= form_for(@todo) do |f| %>
	<%= f.text_field :item %><br />
	<%= f.submit %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "My Tasks", todos_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Markit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  	<link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans+Condensed:300|Pacifico|Architects+Daughter" rel="stylesheet">
  </head>
  <%= render 'layouts/header' %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>About</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center">
	<%= image_tag("markit-logo.png", alt: "Markit logo", class: "logo") %> 
	<h3>Write it down, get it done, mark it off.</h3>
</div>

app/views/todos/_edit_modal.html.erb
<div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
   <h3 id="myModalLabel">Edit</h3>
</div>
<div class="modal-body">
	<%= form_for(@todo) do |f| %>
		<%= f.text_field :item %><br />
		<%= f.submit %>
	<% end %>
</div>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %>
    <%= f.text_field :item %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/_modal.html.erb
<div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
   <h3 id="myModalLabel">New</h3>
</div>
<div class="modal-body">
	<%= form_for @todo do |f| %>
	  	<%= f.text_field :item, :placeholder => "Add new item" %><br />
	  	<%= f.submit %>
	<% end %>
</div>
<!-- <div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	<button class="btn btn-primary">Save changes</button>
</div> -->

app/views/todos/_new_modal.html.erb
<div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
   <h3 id="myModalLabel">New</h3>
</div>
<div class="modal-body">
	<%= form_for @todo, :html => {:class => "form-horizontal center"} do |f| %>
	  	<%= f.text_field :item, :placeholder => "Add new item", class: "input" %><br />
	  	<%= f.submit "Add", class: "btn btn-default btn-primary custom-button" %>
	<% end %>
</div>

app/views/todos/edit.html.erb
<%= form_for @todo, :html => {:class => "form-horizontal center"} do |f| %>
	<%= f.text_field :item, class: "input" %><br />
	<%= f.submit "Edit",  class: "btn btn-default btn-primary custom-button" %>
<% end %>

app/views/todos/edit_modal.js.erb
$("#modal-window").html("<%= escape_javascript(render 'todos/:id/edit') %>");
$('#modal-window').modal('show');

app/views/todos/index.html.erb
<h1>My Tasks</h1>
<div class="container todos"> 
	<table class="table table-hover table bordered">
		<thead>
			<tr>
				<th>Task</th>
			</tr>
		</thead>
		<tbody>
			<% @todos.each do |todo| %>
			<tr>
				<td><%= todo.item %></td>
				<td><%= link_to "Edit", edit_todo_path(todo) %></td>
				<td><%= link_to "Delete", todo, method: :delete %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'New', new_modal_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', :format => :js}  %>

	<div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
</div>

app/views/todos/new.html.erb
<%= form_for @todo do |f| %>
  	<%= f.text_field :item, :placeholder => "Add new item" %><br />
  	<%= f.submit, class: "btn btn-default btn-primary" %>
<% end %>

h2 Edit todo
= form_for(@todo) do |f|
  = f.text_field :item
  = f.submit

 <%= form_for(@todo) do |f| %>
 	<% f.text_field :item, :placeholder => "Edit item" %><br />
 	<%= f.submit,  class: "btn btn-default btn-primary" %>
 <% end %>

app/views/todos/new_modal.js.erb
$("#modal-window").html("<%= escape_javascript(render 'todos/new_modal') %>");
$('#modal-window').modal('show');

app/views/todos/show.html.erb
<div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
   <h3 id="myModalLabel">Modal header</h3>
 </div>
 <div class="modal-body">
   **here comes whatever you want to show!**
 </div>
 <div class="modal-footer">
   <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
   <button class="btn btn-primary">Save changes</button>
 </div>